name: Bug Report
description: Report a bug to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run 'cathartic scan'
        2. ...
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `cathartic --help`
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options: [Linux, macOS, Windows]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      render: shell
